apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud
  namespace: cloud
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany  #读写模式
  resources:
    requests:
      storage: 500Mi
